apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: yourusername/test:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        env:
        - name: GCP_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: gcp-service-account
              key: service-account.json
              optional: true