apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- secret.yaml
generatorOptions:
  disableNameSuffix: true
commonLabels:
  app.kubernetes.io/name: test
  app.kubernetes.io/version: v1.0.0